apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab0-jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      jupyter: lab0
  template:
    metadata:
      labels:
        jupyter: lab0
    spec:
      containers:
      - name: jupyter
        image: node03.st:5000/pyspark-hdfs-jupyter:popletaev-411994
        ports:
        - containerPort: 8282
        command: ["start-notebook.sh"]  # Specify the command to start the Jupyter application
        args:
        - "--NotebookApp.port=8282"  # Set Jupyter to listen on port 8282
        - "--NotebookApp.token=21i7Tp36Of"  # Set Jupyter token to your password
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: jupyter-config
          mountPath: /home/jovyan/.jupyter/jupyter_notebook_config.py
          subPath: jupyter_notebook_config.py
          readOnly: true
      volumes:
      - name: jupyter-config
        configMap:
          name: lab0-jupyter-cm
