apiVersion: v1
kind: Service
metadata:
  name: lab0-jupyter-service
spec:
  type: NodePort
  selector:
    jupyter: lab0
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8282  # Redirect requests to port 8282
    nodePort: 30000  # Choose a NodePort for external access (example)